---
- name: change landing page
  hosts: all
  tasks:
  - name: Creating a file with content
    copy:
      dest: "/var/www/html/index.html"
      content: |
        <!DOCTYPE html>
        <html>
        <head> Welcome to the HTTPD test page </head>
        <body>

        <img src=<img src="https://i2.lensdump.com/i/raHq65.jpg" alt="raHq65.jpg" border="0"><img src="https://i2.lensdump.com/i/raHq65.jpg" alt="raHq65.jpg" border="0">

        </body>
        </html>
      
