---
- name: change landing page
  hosts: all
  tasks:
  - name: Creating a file with content
    copy:
      dest: "/var/www/html/index.html"
      content: |
        <!DOCTYPE html>
        <html>
        <head> Welcome to the HTTPD test page </head>
        <body>

        <a href="https://lensdump.com/i/raHq65"><img src="https://i2.lensdump.com/i/raHq65.jpg" alt="raHq65.jpg" border="0"></a><a href="https://lensdump.com/i/raHq65"><img src="https://i2.lensdump.com/i/raHq65.jpg" alt="raHq65.jpg" border="0"></a>

        </body>
        </html>
      
