---
- name: add Katello and puppet agent 
  hosts: all
  tasks:
  - name: download katello agent
    yum:
      name: katello-agent
      state: present
    
  - name: start and enable goferd
    service: goferd
      state: started
      enabled: yes
    
  - name: download puppet agent
    yum:
      name: puppet
      state: present
    
  - name: start and enable puppet
    service:
      name: puppet
      state: started
      enabled: yes
    
