---
- name: This installs guest agents on VM
  hosts: all
  tasks:
  - name: add RHEL common repo
    rhsm_repository: 
      name: rhel-7-server-rh-common-rpms
   
  - name: install ovirt guest agent
    yum: 
      name: ovirt-guest-agent-common
      state: present
      
  - name: start guest agent
    service: 
      name: ovirt-guest-agent.service 
      state: started
      enabled: yes
      
  - name: start qemu
    service: 
      name: qemu-guest-agent.service 
      state: started
      enabled: yes
