---
- name: This installs guest agents on VM
  hosts: all
  tasks:
  - name: install ovirt guest agent
    yum: name=ovirt-guest-agent-common
  
  - name: start guest agent
    service: name=ovirt-guest-agent.service state=started
   
  - name: enable guest agent
    service: name=ovirt-guest-agent.service state=enabled
      
  - name: start qemu
    service: name=qemu-guest-agent.service state=started
  
  - name: enable qemu
    service: name=qemu-guest-agent.service state=enabled
