---
- name: This removes an httpd webserver
  hosts: all
  tasks:
  - name: stop the httpd service
    service: name=httpd state=stopped
  - name: Close port 80
    firewalld: service=http permanent=false state=disabled
  - name: stop the firewalld service
    service: name=firewalld state=stopped
  - name: remove the httpd rpm
    yum: name=httpd state=removed
  
  
  
  
